language: java

jdk: openjdk8

services:
  - docker
 
addons:
  sauce_connect:
    username: $SAUCELABS_USERNAME
    access_key: $SAUCELABS_ACCESSKEY

cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
  - DB=mysql
  - DB=mariadb

before_cache:
  - rm -rf $HOME/.m2/repository/org/openmrs
 
install: true

script: travis_wait 60 ./travis_script.sh

after_script: ./travis_after_script.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#openmrs"
    on_failure: always
    on_success: change
