language: java

jdk: oraclejdk8

services:
  - docker

addons:
  sauce_connect:
    username: $SAUCELABS_USERNAME
    access_key: $SAUCELABS_ACCESSKEY

before_script: ./travis_before_script.sh

script: travis_wait 50 ./travis_script.sh

after_script: ./travis_after_script.sh
