version: "3.7"

services:
    db:
        image: mariadb:10.3
        command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
        environment:
            MYSQL_DATABASE: openmrs
            MYSQL_USER: ${OPENMRS_DB_USER:-openmrs}
            MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD:-openmrs}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-openmrs}
        volumes:
            - db-data:/var/lib/mysql

    openmrs-refapp:
        image: openmrs/openmrs-referenceapplication:${TAG:-nightly}
        build: .
        depends_on:
            - db
        ports:
            - "8080:8080"
        environment:
            OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
            OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
            OMRS_CONFIG_CREATE_TABLES: "true"
            OMRS_CONFIG_CONNECTION_SERVER: db
            OMRS_CONFIG_CONNECTION_URL: ${OPENMRS_DB_URL}
            OMRS_CONFIG_CONNECTION_DATABASE: ${OPENMRS_DB_NAME:-openmrs}
            OMRS_CONFIG_CONNECTION_USERNAME: ${OPENMRS_DB_USER:-openmrs}
            OMRS_CONFIG_CONNECTION_PASSWORD: ${OPENMRS_DB_PASSWORD:-openmrs}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
            timeout: 5s
        volumes:
            - ./target/openmrs-data:/openmrs/data/:z

volumes:
    db-data:
