# version: "3.7"
secrets:
  m2settings:
    file: ~/.m2/settings.xml
services:
  gateway:
    build:
      context: ./gateway

  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: .
