version: "3.7"

services:
  # Proxy
  proxy:
    build: ./proxy
    ports:
      - 80:80

  # Frontend
  frontend:
    ports:
      - 8081:8080
    build: ./ui
    environment:
      SPA_PATH: /ui
      API_URL: /openmrs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ui"]
      timeout: 5s
    volumes:
      - ./distro/spa:/var/www/ui/

  # OpenMRS:
  openmrs:
    ports:
      - 8080:8080
    build: openmrs/
    depends_on:
      - db
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "true"
      OMRS_CONFIG_CONNECTION_SERVER: db
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: ${OPENMRS_DB_USER}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OPENMRS_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs-data:/openmrs/data
      - ./distro/openmrs_core/:/openmrs/distribution/openmrs_core/
      - ./distro/openmrs_modules:/openmrs/distribution/openmrs_modules/
      - ./distro/openmrs_config:/openmrs/distribution/openmrs_config/

  # MariaDB
  db:
    image: mariadb:10.3
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: ${OPENMRS_DB_USER}
      MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  openmrs-data: ~
  db-data: ~
