name: OHRI Config - Importmap, Deployment

on:
  push:
    branches:
      - dev_config
      - working_config
      - demo_config

  pull_request:
    branches:
      - dev_config
      - working_config
      - demo_config

    types: [opened, synchronize]
  release:
    types:
      - created
jobs:
  update_import_map_dev:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/dev_config' }}

    steps:
      - name: SSH into Dev Server and rename, backup importmap
        uses: garygrossgarten/github-action-ssh@release
        # uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HISTAC_HOST }}
          username: ${{ secrets.HISTAC_USERNAME }}
          privateKey: ${{ secrets.HISTAC_KEY}}
          command: |
            cd /usr/share/tomcat/microfrontends/dev 
            mv importmap.json /path/to/importmap_backup_$(date +"%Y-%m-%d").json

      - name: Copy Branch Dev Import Map to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: config/importmap_dev.json
          remote: /usr/share/tomcat/microfrontends/dev
          host: ${{ secrets.HISTAC_HOST }}
          username: ${{ secrets.HISTAC_USERNAME }}
          privateKey: ${{ secrets.HISTAC_KEY}}
          port: ${{ secrets.HISTAC_PORT }}
