name: OHRI Distro WITH O3 Images

on:
  push:
    tags:
      - "*"
    branches:
      - "*"

  pull_request:
    branches:
      - "*"
    types: [opened, synchronize]
  release:
    types:
      - created

jobs:
  docker_distro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-ohri-distro:working_${{ github.run_number }}
          load: true
          build-args: |
            USERNAME=${{ github.actor }}
            TOKEN=${{ secrets.GITHUB_TOKEN }}
          cache-from: type=inline,ref=user/app:buildcache
          cache-to: type=inline,ref=user/app:buildcache,mode=max
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-ohri-distro:working_${{ github.run_number }}
          cache-from: type=inline,ref=user/app:buildcache
          cache-to: type=inline,ref=user/app:buildcache,mode=max

  run_containers:
    runs-on: ubuntu-latest

    needs: docker_distro

    steps:
      - name: SSH into Azure Ubuntu Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_INSTANCE }}
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}
          script: |
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker run -d -p 8080:8080 ${DOCKERHUB_USERNAME}/openmrs3-backend:staging

      - name: Wait for server to start
        run: sleep 30

  sandbox:
    runs-on: ubuntu-latest

    needs: docker_distro

    if: ${{ github.ref == 'refs/heads/working' }}

    steps:
      # Update the Microfrontends to reflect what we have in the Working branch
      - uses: garygrossgarten/github-action-ssh@release
        name: Run the Update MicroFronEnd Script
        with:
          command: cd /usr/share/tomcat/distro/sandbox && docker run ${{ secrets.DOCKERHUB_USERNAME }}/openmrs-esm-ohri-frontend:ci
          host: ${{ secrets.HISTAC_HOST }}
          username: ${{ secrets.HISTAC_USERNAME }}
          privateKey: ${{ secrets.HISTAC_KEY}}
          port: ${{ secrets.HISTAC_PORT }}

  #dev_3_ohri job, the tags property for the docker/build-push-action step is updated to include ${{ github.run_number }}, which is a unique identifier for each run. This will tag the dev image with an incremental count.

  #working_3_ohri job, the tags property for the docker/build-push-action step is updated to include ${{ github.run_number }}, which will tag the image with the runner timestamp. Also, the if property is updated to check for the working_3_ohri branch, and the `needs

  working_3_ohri:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-last, macos-latest]

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/working_3_ohri' }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-backend:working_${{ github.run_number }}
      - name: Save image digest
        run: echo "::set-output name=image::${{ steps.build-and-push.outputs.digest }}"

  dev_3_ohri:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    needs: working_3_ohri

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev_3_ohri' }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: build-an-push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openmrs3-backend:dev-${{ github.run_number}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Save image digest
        run: echo "::set-output name=image::${{ steps.build-and-push.output.digest }}"
